services:
  tool:
    privileged: true
    build: .
    develop:
      watch:
        - action: rebuild
          path: backend/.
        - action: rebuild
          path: frontend/.
          ignore:
            - node_modules
    network_mode: host
    environment:
      DNS_SERVER: "1.1.1.1"
      PORT: "8080"
#      HTTPS_HOST: "k.localhost"
    volumes:
      - "./regions.development.yml:/var/app/regions.yml"
    ports:
      - "8080:8080"
